spring.application.name=event-sourced-ledger
server.port=8080

spring.datasource.url=${LEDGER_DB_URL:jdbc:postgresql://localhost:5432/ledger_db}
spring.datasource.username=${LEDGER_DB_USERNAME}
spring.datasource.password=${LEDGER_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true